
// Connection.cpp

// Interfaces to the cConnection class representing a single pair of connected sockets,
// understanding the Minecraft protocol version 340 (MC 1.12.2).
//
// The proxy taps the connection between a client and a server:
//   - everything the server sends is decrypted (if encrypted), decoded into the log and relayed to the
//     client as-is, so that the client keeps talking to an unencrypted proxy,
//   - everything the client sends is decoded into the log and relayed to the server, encrypted with the
//     key that the proxy negotiated with the server itself.
// The handshake's port is rewritten to the real server's port, and the encryption request that the
// server sends is replaced by an encryption response generated by the proxy - see
// SendEncryptionKeyResponse() below.





#include "Globals.h"
#include "Connection.h"
#include "Server.h"
#include <iostream>
#include "mbedTLS++/CryptoKey.h"
#include "../../src/Logger.h"

#ifdef _WIN32
	#include <direct.h>  // For _mkdir()
#else
	#include <sys/stat.h>   // for mkdir
#endif





/** Reads one VarInt-prefixed byte array into a_Value. */
static bool ReadRawByteArray(cPayloadReader & a_Reader, ContiguousByteBuffer & a_Value)
{
	Int64 Length;
	if (!a_Reader.ReadVarIntValue(Length) || (Length < 0) || (static_cast<size_t>(Length) > a_Reader.GetRemainingBytes()))
	{
		return false;
	}
	a_Value.assign(a_Reader.GetRemaining().data(), static_cast<size_t>(Length));
	return a_Reader.SkipBytes(static_cast<size_t>(Length));
}





/** The protocol version this proxy understands, wiki.vg "Protocol version numbers" for MC 1.12.2. */
static constexpr UInt32 ProxyProtocolVersion = 340;





////////////////////////////////////////////////////////////////////////////////
// cConnection:

cConnection::cConnection(SOCKET a_ClientSocket, cServer & a_Server):
	m_LogFile(nullptr),
	m_Server(a_Server),
	m_ClientSocket(a_ClientSocket),
	m_ServerSocket(-1),
	m_BeginTick(std::chrono::steady_clock::now()),
	m_ServerProtocolState(psUnknown),
	m_ClientProtocolState(psUnknown),
	m_IsServerEncrypted(false),
	m_NBTFileIdx(0)
{
	// Create the Logs subfolder, if not already created:
	#if defined(_WIN32)
		_mkdir("Logs");
	#else
		mkdir("Logs", 0777);
	#endif

	m_LogNameBase = fmt::format(FMT_STRING("Logs/Log_{}_{}"), time(nullptr), a_ClientSocket);
	AString fnam(m_LogNameBase);
	fnam.append(".log");
	#ifdef _WIN32
		fopen_s(&m_LogFile, fnam.c_str(), "w");
	#else
		m_LogFile = fopen(fnam.c_str(), "w");
	#endif
	Log("Log file created, ProtoProxy decoding protocol {}", ProxyProtocolVersion);
	fmt::print(FMT_STRING("Connection is logged to file \"{}\"\n"), fnam);
}





cConnection::~cConnection()
{
	if (m_LogFile != nullptr)
	{
		fclose(m_LogFile);
	}
}





void cConnection::Run(void)
{
	if (!ConnectToServer())
	{
		Log("Cannot connect to server; aborting");
		return;
	}

	while (true)
	{
		fd_set ReadFDs;
		FD_ZERO(&ReadFDs);
		FD_SET(m_ServerSocket, &ReadFDs);
		FD_SET(m_ClientSocket, &ReadFDs);
		SOCKET MaxSocket = std::max(m_ServerSocket, m_ClientSocket);
		int res = select(MaxSocket + 1, &ReadFDs, nullptr, nullptr, nullptr);
		if (res <= 0)
		{
			printf("select() failed: %d; aborting client\n", SocketError);
			break;
		}
		if (FD_ISSET(m_ServerSocket, &ReadFDs))
		{
			if (!RelayFromServer())
			{
				break;
			}
		}
		if (FD_ISSET(m_ClientSocket, &ReadFDs))
		{
			if (!RelayFromClient())
			{
				break;
			}
		}
	}
	Log("Relaying ended, closing sockets");
	LogFlush();
	closesocket(m_ServerSocket);
	closesocket(m_ClientSocket);
}





void cConnection::vLog(const char * a_Format, fmt::format_args a_ArgList)
{
	if (m_LogFile == nullptr)
	{
		return;
	}

	// Format the message first, so that the file gets a single line written under the lock:
	AString Message;
	try
	{
		fmt::vformat_to(std::back_inserter(Message), a_Format, a_ArgList);
	}
	catch (const std::runtime_error &)
	{
		Message = a_Format;
	}

	cCSLock Lock(m_CSLog);
	fmt::fprintf(m_LogFile, "[%5.3f] %s\n", GetRelativeTime(), Message.c_str());
	fflush(m_LogFile);
}





void cConnection::vDataLog(const void * a_Data, size_t a_Size, const char * a_Format, fmt::format_args a_ArgList)
{
	if (m_LogFile == nullptr)
	{
		return;
	}
	AString Message;
	try
	{
		fmt::vformat_to(std::back_inserter(Message), a_Format, a_ArgList);
	}
	catch (const std::runtime_error &)
	{
		Message = a_Format;
	}
	AString Hex;
	CreateHexDump(Hex, a_Data, a_Size, 16);

	cCSLock Lock(m_CSLog);
	fmt::fprintf(m_LogFile, "[%5.3f] %s\n%s\n", GetRelativeTime(), Message.c_str(), Hex.c_str());
	fflush(m_LogFile);
}



void cConnection::LogFlush(void)
{
	if (m_LogFile != nullptr)
	{
		fflush(m_LogFile);
	}
}





bool cConnection::ConnectToServer(void)
{
	m_ServerSocket = socket(AF_INET, SOCK_STREAM, IPPROTO_TCP);
	if (m_ServerSocket == INVALID_SOCKET)
	{
		return false;
	}
	sockaddr_in localhost;
	localhost.sin_family = AF_INET;
	localhost.sin_port = htons(m_Server.GetConnectPort());
	localhost.sin_addr.s_addr = htonl(0x7f000001);  // localhost
	if (connect(m_ServerSocket, reinterpret_cast<const sockaddr *>(&localhost), sizeof(localhost)) != 0)
	{
		printf("connection to server on port %d failed: %d\n", m_Server.GetConnectPort(), SocketError);
		return false;
	}
	Log("Connected to SERVER on port {}", m_Server.GetConnectPort());
	return true;
}





bool cConnection::RelayFromServer(void)
{
	char Buffer[64 KiB];
	int res = static_cast<int>(recv(m_ServerSocket, Buffer, sizeof(Buffer), 0));  // recv returns int on Windows, ssize_t on Linux
	if (res <= 0)
	{
		Log("Server closed the socket: {}; {} (0x{:x}); aborting connection", res, SocketError, static_cast<unsigned>(SocketError));
		return false;
	}

	DataLog(Buffer, static_cast<size_t>(res), "Received {} bytes from the SERVER", res);
	return ProcessData(dirFromServer, Buffer, static_cast<size_t>(res));
}





bool cConnection::RelayFromClient(void)
{
	char Buffer[64 KiB];
	int res = static_cast<int>(recv(m_ClientSocket, Buffer, sizeof(Buffer), 0));  // recv returns int on Windows, ssize_t on Linux
	if (res <= 0)
	{
		Log("Client closed the socket: {}; {} (0x{:x}); aborting connection", res, SocketError, static_cast<unsigned>(SocketError));
		return false;
	}

	DataLog(Buffer, static_cast<size_t>(res), "Received {} bytes from the CLIENT", res);
	return ProcessData(dirFromClient, Buffer, static_cast<size_t>(res));
}





double cConnection::GetRelativeTime(void)
{
	Int64 msec = std::chrono::duration_cast<std::chrono::milliseconds>(std::chrono::steady_clock::now() - m_BeginTick).count();
	return static_cast<double>(msec) / 1000;
}





bool cConnection::SendData(SOCKET a_Socket, const ContiguousByteBufferView a_Data, const char * a_Peer)
{
	DataLog(a_Data.data(), a_Data.size(), "Sending data to {}, {} bytes", a_Peer, a_Data.size());

	int res = static_cast<int>(send(a_Socket, reinterpret_cast<const char *>(a_Data.data()), a_Data.size(), 0));  // Windows uses int for a_Size, Linux uses size_t; return type is int on Windows, ssize_t on Linux
	if (res <= 0)
	{
		Log("{} closed the socket: {}, {}; aborting connection", a_Peer, res, SocketError);
		return false;
	}
	return true;
}





bool cConnection::SendEncryptedData(SOCKET a_Socket, cAesCfb128Encryptor & a_Encryptor, ContiguousByteBuffer & a_Data, const char * a_Peer)
{
	DataLog(a_Data.data(), a_Data.size(), "Encrypting {} bytes to {}", a_Data.size(), a_Peer);

	a_Encryptor.ProcessData(a_Data.data(), a_Data.size());
	return SendData(a_Socket, a_Data, a_Peer);
}





bool cConnection::ProcessData(eDirection a_Direction, const char * a_Data, size_t a_Size)
{
	ContiguousByteBuffer Decrypted;
	ContiguousByteBufferView Bytes(reinterpret_cast<const std::byte *>(a_Data), a_Size);
	if ((a_Direction == dirFromServer) && m_IsServerEncrypted)
	{
		Decrypted.assign(Bytes.data(), Bytes.size());
		m_ServerDecryptor.ProcessData(Decrypted.data(), Decrypted.size());
		DataLog(Decrypted.data(), Decrypted.size(), "Decrypted {} bytes from the SERVER", Decrypted.size());
		Bytes = ContiguousByteBufferView(Decrypted);
	}

	auto & Stream = (a_Direction == dirFromClient) ? m_PacketsFromClient : m_PacketsFromServer;
	Stream.AddData(Bytes.data(), Bytes.size());
	sCapturedPacket Packet;
	while (Stream.NextPacket(Packet))
	{
		if (!HandlePacket(a_Direction, Packet))
		{
			return false;
		}
	}
	if (Stream.HasError())
	{
		Log("The {} stream contains a packet that cannot be decoded, the framing is out of sync; closing",
			(a_Direction == dirFromClient) ? "client" : "server");
		return false;
	}
	return true;
}





void cConnection::LogPacket(
	eDirection a_Direction,
	const sCapturedPacket & a_Packet,
	eProtocolState a_State,
	const cPacketDefinition * a_Definition
)
{
	static const char * const g_DirectionNames[] = { "C->S", "S->C" };
	if (a_Definition == nullptr)
	{
		DataLog(a_Packet.m_Payload.data(), a_Packet.m_Payload.size(), "Unknown {} packet 0x{:02x} in state {}, {} bytes, relaying unchanged",
			g_DirectionNames[a_Direction], a_Packet.m_PacketID, cPacketLayout::GetStateName(a_State),
			a_Packet.m_Payload.size());
		return;
	}

	Log("{} {} (0x{:02x}, {} bytes{})",
		g_DirectionNames[a_Direction], a_Definition->m_Name, a_Packet.m_PacketID,
		a_Packet.m_Payload.size(), a_Packet.m_IsCompressed ? ", compressed" : ""
	);

	cPayloadReader Reader(a_Packet.m_Payload.data(), a_Packet.m_Payload.size());
	Reader.SetNBTFilePrefix(fmt::format(FMT_STRING("{}_{}"), m_LogNameBase, m_NBTFileIdx));
	for (const cPacketField * Field = a_Definition->m_Fields; Field->m_Name != nullptr; Field++)
	{
		AString Value;
		if (!Reader.ReadField(*Field, Value))
		{
			Log("  {}: <incomplete packet, {} bytes left>", Field->m_Name, Reader.GetRemainingBytes());
			return;
		}
		// Values of compound fields span several lines, keep them indented under the field:
		size_t LineStart = 0;
		while (LineStart <= Value.size())
		{
			auto LineEnd = Value.find('\n', LineStart);
			if (LineEnd == AString::npos)
			{
				LineEnd = Value.size();
			}
			if (LineStart == 0)
			{
				Log("  {} = {}", Field->m_Name, Value.substr(LineStart, LineEnd - LineStart));
			}
			else
			{
				Log("    {}", Value.substr(LineStart, LineEnd - LineStart));
			}
			LineStart = LineEnd + 1;
			if (LineEnd == Value.size())
			{
				break;
			}
		}
	}
	if (Reader.GetRemainingBytes() > 0)
	{
		Log("  {} payload bytes left over, the proxy's layout is out of date", Reader.GetRemainingBytes());
	}
}





bool cConnection::HandlePacket(eDirection a_Direction, const sCapturedPacket & a_Packet)
{
	const bool IsFromClient = (a_Direction == dirFromClient);
	const eProtocolState State = IsFromClient ? m_ClientProtocolState : m_ServerProtocolState;

	// The packets that the proxy cannot just relay need to be handled before anything else:
	if (IsFromClient && (State == psUnknown) && (a_Packet.m_PacketID == 0x00))
	{
		return HandleHandshake(a_Packet);
	}
	if (!IsFromClient && (State == psLogin) && (a_Packet.m_PacketID == 0x01))
	{
		return HandleEncryptionRequest(a_Packet);
	}

	const auto Definition = IsFromClient
		? cPacketLayout::GetFromClientLayout(State, a_Packet.m_PacketID)
		: cPacketLayout::GetFromServerLayout(State, a_Packet.m_PacketID);
	LogPacket(a_Direction, a_Packet, State, Definition);

	if (!IsFromClient && (State == psLogin))
	{
		if (a_Packet.m_PacketID == 0x03)
		{
			HandleSetCompression(a_Packet.m_Payload);
		}
		else if (a_Packet.m_PacketID == 0x02)
		{
			HandleLoginSuccess();
		}
	}

	if (IsFromClient)
	{
		// Everything the client sent goes to the server, encrypted once the server demanded it:
		ContiguousByteBuffer ToServer(a_Packet.m_Raw.data(), a_Packet.m_Raw.size());
		if (m_IsServerEncrypted)
		{
			if (!SendEncryptedData(m_ServerSocket, m_ServerEncryptor, ToServer, "Server"))
			{
				return false;
			}
		}
		else if (!SendData(m_ServerSocket, a_Packet.m_Raw, "Server"))
		{
			return false;
		}
	}
	else
	{
		// The client connection is never encrypted, so the bytes go out as they came in:
		if (!SendData(m_ClientSocket, a_Packet.m_Raw, "Client"))
		{
			return false;
		}
	}
	LogFlush();
	return true;
}





bool cConnection::HandleHandshake(const sCapturedPacket & a_Packet)
{
	// wiki.vg Protocol#Handshake, protocol 340: VarInt version, String address, UShort port, VarInt next state:
	cPayloadReader Reader(a_Packet.m_Payload.data(), a_Packet.m_Payload.size());
	Int64 ProtocolVersion = 0;
	Int64 NextState = 0;
	AString Address;
	UInt16 Port = 0;
	if (
		!Reader.ReadVarIntValue(ProtocolVersion) ||
		!Reader.ReadStringValue(Address) ||
		!Reader.ReadUShortValue(Port) ||
		!Reader.ReadVarIntValue(NextState)
	)
	{
		Log("C->S Handshake: cannot parse, relaying unchanged");
		return SendData(m_ServerSocket, a_Packet.m_Raw, "Server");
	}
	Log("C->S Handshake (0x00): protocol {}, address \"{}\", port {}, next state {}",
		ProtocolVersion, Address, Port, NextState);
	if (ProtocolVersion != static_cast<Int64>(ProxyProtocolVersion))
	{
		Log("  WARNING: the client announced protocol {}, this proxy decodes {}", ProtocolVersion, ProxyProtocolVersion);
	}

	if ((NextState < 1) || (NextState > 3))
	{
		Log("  unknown next state, keeping the connection in the handshaking state");
		return SendData(m_ServerSocket, a_Packet.m_Raw, "Server");
	}
	m_ClientProtocolState = static_cast<eProtocolState>(NextState);
	m_ServerProtocolState = static_cast<eProtocolState>(NextState);

	// Rebuild the packet with the port replaced by the one we actually connect to:
	ContiguousByteBuffer Payload;
	WriteVarIntTo(Payload, static_cast<UInt64>(ProtocolVersion));
	WriteVarIntTo(Payload, Address.size());
	Payload.append(reinterpret_cast<const std::byte *>(Address.data()), Address.size());
	Payload.push_back(static_cast<std::byte>((m_Server.GetConnectPort() >> 8) & 0xff));
	Payload.push_back(static_cast<std::byte>(m_Server.GetConnectPort() & 0xff));
	WriteVarIntTo(Payload, static_cast<UInt64>(NextState));
	ContiguousByteBuffer ToServer;
	m_ToServer.Serialize(0x00, Payload, ToServer);
	Log("  rewritten to port {}, state {}", m_Server.GetConnectPort(), cPacketLayout::GetStateName(m_ServerProtocolState));
	return SendData(m_ServerSocket, ToServer, "Server");
}





void cConnection::HandleSetCompression(const ContiguousByteBufferView a_Payload)
{
	cPayloadReader Reader(a_Payload.data(), a_Payload.size());
	static const cPacketField g_fThreshold{"Threshold", ftVarInt};
	AString Value;
	if (!Reader.ReadField(g_fThreshold, Value))
	{
		Log("  Set Compression: cannot parse the threshold, compression left untouched");
		return;
	}
	const auto Threshold = static_cast<Int32>(atoi(Value.c_str()));
	// Both directions follow the same threshold, wiki.vg Protocol#Set Compression:
	m_PacketsFromServer.SetThreshold(Threshold);
	m_PacketsFromClient.SetThreshold(Threshold);
	m_ToServer.SetThreshold(Threshold);
	Log("  compression {} from now on, threshold {}", (Threshold < 0) ? "off" : "on", Threshold);
}





void cConnection::HandleLoginSuccess(void)
{
	Log("  both connections are now in the game state");
	m_ServerProtocolState = psGame;
	m_ClientProtocolState = psGame;
	if (m_IsServerEncrypted)
	{
		Log("  the server connection is encrypted, the client connection is not");
	}
	if (!m_ServerEncryptionBuffer.empty())
	{
		Log("  sending {} bytes that were queued while waiting for encryption", m_ServerEncryptionBuffer.size());
		SendEncryptedData(m_ServerSocket, m_ServerEncryptor, m_ServerEncryptionBuffer, "Server");
		m_ServerEncryptionBuffer.clear();
	}
}





bool cConnection::HandleEncryptionRequest(const sCapturedPacket & a_Packet)
{
	// wiki.vg Protocol#Encryption Request, protocol 340:
	cPayloadReader Reader(a_Packet.m_Payload.data(), a_Packet.m_Payload.size());
	static const cPacketField g_fServerID{"Server ID", ftString};
	static const cPacketField g_fPublicKey{"Public Key", ftByteArray};
	static const cPacketField g_fToken{"Verify Token", ftByteArray};
	AString ServerID, PublicKeySize, TokenSize;
	if (
		!Reader.ReadField(g_fServerID, ServerID) ||
		!Reader.ReadField(g_fPublicKey, PublicKeySize) ||
		!Reader.ReadField(g_fToken, TokenSize)
	)
	{
		Log("S->C Encryption Request (0x01): cannot parse, aborting the connection");
		return false;
	}
	Log("S->C Encryption Request (0x01): server id {}, {} bytes of public key, {} bytes of verify token",
		ServerID, PublicKeySize, TokenSize);
	Log("  not relaying to the client, the proxy answers on its own");

	// Re-read the raw values of the two byte arrays, the decoded ones are formatted for humans:
	cPayloadReader Raw(a_Packet.m_Payload.data(), a_Packet.m_Payload.size());
	AString Ignored;
	if (!Raw.ReadStringValue(Ignored))
	{
		return false;
	}
	ContiguousByteBuffer PublicKey;
	ContiguousByteBuffer Token;
	if (!ReadRawByteArray(Raw, PublicKey) || !ReadRawByteArray(Raw, Token))
	{
		Log("  the encryption request is malformed, aborting the connection");
		return false;
	}

	return SendEncryptionKeyResponse(PublicKey, Token);
}





bool cConnection::SendEncryptionKeyResponse(const ContiguousByteBufferView a_ServerPublicKey, const ContiguousByteBufferView a_VerifyToken)
{
	// The proxy needs a shared secret it knows, so it offers an all-zero one, encrypted with the
	// server's own public key. The client is never told about encryption and keeps talking in clear text.
	Byte SharedSecret[16];
	Byte EncryptedSecret[1024];
	Byte EncryptedToken[1024];
	memset(SharedSecret, 0, sizeof(SharedSecret));
	const AString KeyString(reinterpret_cast<const char *>(a_ServerPublicKey.data()), a_ServerPublicKey.size());
	cCryptoKey PubKey(KeyString);
	int res = PubKey.Encrypt(SharedSecret, sizeof(SharedSecret), EncryptedSecret, sizeof(EncryptedSecret));
	if (res < 0)
	{
		Log("  shared secret encryption failed: {} (0x{}), aborting the connection", res, res);
		return false;
	}
	const int TokenRes = PubKey.Encrypt(
		reinterpret_cast<const Byte *>(a_VerifyToken.data()), a_VerifyToken.size(), EncryptedToken, sizeof(EncryptedToken)
	);
	if (TokenRes < 0)
	{
		Log("  verify token encryption failed: {} (0x{}), aborting the connection", TokenRes, TokenRes);
		return false;
	}

	m_ServerEncryptor.Init(SharedSecret, SharedSecret);
	m_ServerDecryptor.Init(SharedSecret, SharedSecret);

	// wiki.vg Protocol#Encryption Response: two VarInt-prefixed byte arrays:
	ContiguousByteBuffer Payload;
	WriteVarIntTo(Payload, sizeof(EncryptedSecret));
	Payload.append(reinterpret_cast<const std::byte *>(EncryptedSecret), sizeof(EncryptedSecret));
	WriteVarIntTo(Payload, static_cast<UInt64>(TokenRes));
	Payload.append(reinterpret_cast<const std::byte *>(EncryptedToken), static_cast<size_t>(TokenRes));
	ContiguousByteBuffer ToServer;
	m_ToServer.Serialize(0x01, Payload, ToServer);
	DataLog(EncryptedSecret, sizeof(EncryptedSecret), "  encrypted shared secret, {} bytes", static_cast<unsigned>(sizeof(EncryptedSecret)));
	if (!SendData(m_ServerSocket, ToServer, "Server"))
	{
		return false;
	}
	m_IsServerEncrypted = true;
	Log("  server connection encryption started, the queue of client data is now encrypted as well");
	return true;
}
